rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 1.9.3
  - rbx
matrix:
  include:
    - rvm: ruby-2.2.5
      os: osx
      osx_image: xcode7.3
    - rvm: ruby-2.2.5
      os: osx
      osx_image: xcode6.4
    - rvm: ruby-2.2.2
      os: osx
      osx_image: beta-xcode6.2
    - rvm: ruby-2.3.1-clang
      env: CXX=clang++
    - rvm: ree
    - rvm: ruby-1.8.7
  allow_failures:
    - rvm: ree
    - rvm: ruby-1.8.7
  fast_finish: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX=g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo gem install bundler ; fi
script:
  - MAKEFLAGS+=-j8 bundle exec rake spec build binary --trace
  - MAKEFLAGS+=-j8 travis_wait gem install pkg/*.gem
deploy:
  provider: releases
  file: $(git ls-files -o pkg | head -1)
  api_key:
    secure: OMCBceg89uRnU+FIPAPbeOK2pISvV4Cz62r9iTRIGXQCOOXX8M40i77/3DmtkMtc9FEuNyAu1+CH886PL2WtZZPK4CmEU3HuqXz1a5VsCI+zcAZL1tevKvblXOVQ3MG+B/SZRC3rEzGwjk4027WtzCCGoGCLUu4TFJP05+/8XN4=
  skip_cleanup: true
  on:
    tags: true
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
