rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 1.9.3
  - rbx
matrix:
  include:
    - rvm: system
      os: osx
      osx_image: xcode7.3
    - rvm: system
      os: osx
      osx_image: xcode6.4
    - rvm: system
      os: osx
      osx_image: beta-xcode6.2
bundler_args: --jobs=1 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git-svn; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo gem install bundler ; fi
script:
  - MAKEFLAGS+=-j8 bundle exec rake checkout compile spec binary --trace
deploy:
  provider: releases
  file: $(git ls-files -o pkg | head -1)
  api_key:
    secure: OMCBceg89uRnU+FIPAPbeOK2pISvV4Cz62r9iTRIGXQCOOXX8M40i77/3DmtkMtc9FEuNyAu1+CH886PL2WtZZPK4CmEU3HuqXz1a5VsCI+zcAZL1tevKvblXOVQ3MG+B/SZRC3rEzGwjk4027WtzCCGoGCLUu4TFJP05+/8XN4=
  skip_cleanup: true
  on:
    tags: true
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
