language: ruby
rvm:
  - 2.2.2
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - rbx-2
bundler_args: -j4
script:
  - bundle exec rake spec build binary --trace
  - travis_wait gem install pkg/*.gem
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
cache: bundler
env: CXX=clang++
